server:
  port: 8050
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker #Nombre de la rama en la cual quiero que trabaje
          uri: https://github.com/LewisAlvarez/SpringBoot
          search-paths: config-data #CArdeta donde se encuentran los archivos con la configuracion de los microservicios
  application:
    name: config-service
