server:
  port: 8050
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server #Nombre de la rama en la cual quiero que trabajo
          uri: https://github.com/LewisAlvarez/SpringBoot.git
          search-paths: config-data #Archivos con la configuracion de los microservicios
  application:
    name: config-service
